name: Build, test and deploy ASP.Net Core app to Azure Web App - bdsagroup18chirpweb
run-name: ðŸš€ Deploying ${{ github.sha }} by ${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Restore
        run: dotnet restore ./src/Chirp.Web/Chirp.Web.csproj

      - name: Build
        run: dotnet build ./src/Chirp.Web/Chirp.Web.csproj --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test ./test/Chirp.Core.Tests/Chirp.Core.Tests.csproj --configuration Release --no-restore --no-build -v detailed
          dotnet test ./test/Chirp.Infrastructure.Tests/Chirp.Repositories.Tests/Chirp.Repositories.Tests.csproj --configuration Release --no-restore --no-build -v detailed
          dotnet test ./test/Chirp.Web.Tests/Chirp.Web.Tests.csproj --configuration Release --no-restore --no-build -v detailed

      - name: Publish with dotnet (for Linux, as self-contained or framework-dependent)
        run: |
          dotnet publish ./src/Chirp.Web/Chirp.Web.csproj \
            --configuration Release \
            --output ${{ github.workspace }}/publish \
            /p:PublishReadyToRun=false \
            /p:PublishSingleFile=false \
            /p:RuntimeIdentifier=linux-x64 \
            /p:SelfContained=false

      - name: Remove Data folder from publish
        run: rm -rf ${{ github.workspace }}/publish/Data

      - name: Zip published output
        run: |
          cd ${{ github.workspace }}/publish
          zip -r ../Chirp.Web.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: chirp-web-zip
          path: ${{ github.workspace }}/Chirp.Web.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-publish
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: chirp-web-zip
          path: ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C1C35E035324957B084B6DE34A1610A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA6FB8EEB4994F1D949A46622B91FF5A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08CF315808804A7C81FFA986C932FFCC }}

      - name: Deploy to Azure Web App via ZIP with clean
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "bdsagroup18chirpweb"
          slot-name: "Production"
          package: ./artifact/Chirp.Web.zip

      - name: Logout of Azure
        run: az logout
